### ISSUE TITLE
Typo in package name?

### ISSUE THREAD

**Issue by mxcl** [gumob/PunycodeSwift#13]
The main product is defined as `Punnycode` in the Package.swift. This made figuring out how to install it tricky.

**Comment by mxcl** [comment]
For others that ran into the same issue, this is what you have to do to depend on this package:

```swift
pkg.dependencies.append(.package(name: "Punycode", url: "https://github.com/gumob/PunycodeSwift", from: "2.0.0"))
pkg.targets.append(.target(
    name: "foo",
    dependencies: [
        .product(name: "Punnycode", package: "Punycode")
    ]))
```

**Comment by case** [comment]
I just ran into this as well.

@gumob would you consider updating the Package Name here?

**Comment by HolzmannDaniel** [comment]
@gumob That's in theory BCH now, I was just trying to update my packages which failed as it couldn't find the package anymore.

Edit:
Actually as long as https://github.com/gumob/TLDExtractSwift isn't updated as well, it's a BCH

**Comment by tremblay** [comment]
I see this rename was just completed. For future reference, renaming a package should probably be a major version bump, since it breaks SPM's ability to resolve. I've opened a [PR](https://github.com/gumob/TLDExtractSwift/pull/12) to resolve the issue in TLDExtract, but you could consider reverting the naming change (as 2.1.2) and then re-implementing it along with a major version bump (3.0.0).

**Comment by gumob** [comment]
I am currently in the process of updating [PunycodeSwift](https://github.com/gumob/PunycodeSwift) to the latest version, and we plan to update [TLDExtractSwift](https://github.com/gumob/TLDExtractSwift) in the near future as well.

For now, I have merged the [PR](https://github.com/gumob/TLDExtractSwift/pull/12), but if you encounter any build failures, please leave a comment, and I will roll back PunycodeSwift.
